unite_metric:
  class_path: comet.models.UniTEMetric
  init_args:
    nr_frozen_epochs: 0.3
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 5.0e-06
    learning_rate: 1.5e-05
    layerwise_decay: 0.95
    encoder_model: RemBERT
    pretrained_model: google/rembert
    pool: cls
    layer: mix
    loss: mse
    dropout: 0.1
    batch_size: 4
    train_data: 
      - data/1719-da.csv
    validation_data: 
      - data/qad-ende-newstest2020.csv
      - data/qad-enru-newstest2020.csv
      - data/wmt-ende-newstest2020.csv
      - data/wmt-zhen-newstest2020.csv
    hidden_sizes:
      - 3456
      - 1152
    activations: Tanh
    input_segments:
      - mt
      - ref
    
trainer: ../trainer.yaml
early_stopping: ../early_stopping.yaml
model_checkpoint: ../model_checkpoint.yaml
