regression_metric:
  class_path: comet.models.RegressionMetric
  init_args:
    nr_frozen_epochs: 0.3
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 3.0e-06
    learning_rate: 1.5e-05
    layerwise_decay: 0.95
    encoder_model: XLM-RoBERTa
    pretrained_model: xlm-roberta-large
    layer_transformation: softmax
    pool: avg
    layer: mix
    loss: mse
    dropout: 0.1
    batch_size: 2
    train_data:
      - data/MQM/google-schema.train.csv
    validation_data:
      - data/MQM/wmt-ende-newstest2021.csv
      - data/MQM/wmt-zhen-newstest2021.csv
      - data/MQM/wmt-enru-newstest2021.csv
    hidden_sizes:
      - 3072
      - 1024
    activations: Tanh
    
trainer: trainer.yaml
early_stopping: early_stopping.yaml
model_checkpoint: model_checkpoint.yaml
